#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/heitor/neuron/nrn-7.4"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/heitor/neuron/nrn-7.4/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/heitor/Dropbox/Unicamp/reproducible/dev/x86_64/.libs/libnrnmech.so" "$@"
