#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/work/nrn-7.4"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/work/nrn-7.4/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/work/reproducible/deliver/x86_64/.libs/libnrnmech.so" "$@"
